# Generated by Django 4.2 on 2025-08-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='account_holder_name',
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='account_holder_first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='account_holder_last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='account_type',
            field=models.CharField(choices=[('default', 'Default'), ('custom', 'Custom')], default='custom', max_length=10, null=True),
        ),
    ]
