# Generated by Django 5.2.5 on 2025-08-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
