# Generated by Django 5.2.5 on 2025-08-08 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0002_remove_bankdetails_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='bank_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='adminModule.bankdetails'),
        ),
    ]
