# Generated by Django 5.2.5 on 2025-09-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0002_project_current_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='email_app_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
