# Generated by Django 5.2.5 on 2025-08-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0003_remove_bankdetails_project_project_bank_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phn', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('institution_img', models.ImageField(blank=True, null=True, upload_to='institution_img/')),
                ('table_status', models.BooleanField(default=True)),
            ],
        ),
    ]
