# Generated by Django 5.2.5 on 2025-09-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0003_institution_email_app_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_goal',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='project',
            name='tile_value',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
