# Generated by Django 5.2.5 on 2025-08-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0004_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='account_type',
        ),
    ]
