# Generated by Django 5.2.5 on 2025-10-08 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0004_alter_project_current_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='default_bank',
        ),
        migrations.RemoveField(
            model_name='project',
            name='bank_details',
        ),
        migrations.AddField(
            model_name='institution',
            name='default_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminModule.bankdetails'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminModule.institution'),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
