# Generated by Django 5.2.5 on 2025-10-09 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0005_remove_customuser_default_bank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='closing_date',
            new_name='closed_by',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='created_at',
            new_name='started_at',
        ),
    ]
