# Generated by Django 5.2.5 on 2025-08-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0006_project_created_by_alter_project_bank_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
