# Generated by Django 5.2.5 on 2025-08-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0006_project_created_by_alter_project_bank_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='account_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
