# Generated by Django 5.2.5 on 2025-10-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0006_rename_closing_date_project_closed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='closed_by',
            field=models.DateTimeField(null=True),
        ),
    ]
