# Generated by Django 5.2.5 on 2025-08-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0007_alter_bankdetails_account_no_and_more'),
        ('adminModule', '0007_project_qr_code'),
    ]

    operations = [
    ]
