# Generated by Django 5.2.5 on 2025-10-16 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0008_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_prefs', serialize=False, to='adminModule.institution', verbose_name='Institution')),
                ('sms_enabled', models.BooleanField(default=True, verbose_name='SMS Notifications')),
                ('whatsapp_enabled', models.BooleanField(default=True, verbose_name='WhatsApp Notifications')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email Notifications')),
            ],
        ),
    ]
