# Generated by Django 5.2.5 on 2025-10-30 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0009_notificationpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_title', models.CharField(max_length=100)),
                ('update', models.TextField()),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('table_status', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='adminModule.project')),
            ],
        ),
    ]
