# Generated by Django 5.2.5 on 2025-08-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='upi_id',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
