# Generated by Django 5.2.5 on 2025-08-13 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0003_remove_bankdetails_project_project_bank_details'),
        ('userModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phn_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_pics/'),
        ),
        migrations.CreateModel(
            name='SelectedTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiles', models.CharField(max_length=255)),
                ('funded_at', models.DateTimeField(auto_now_add=True)),
                ('table_status', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='adminModule.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_tiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
