# Generated by Django 5.2.5 on 2025-08-13 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0004_institution'),
        ('userModule', '0002_alter_customuser_email_alter_customuser_phn_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminModule.institution'),
        ),
    ]
