# Generated by Django 5.2.5 on 2025-08-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0002_remove_transaction_upi_id_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
