# Generated by Django 5.2.5 on 2025-08-13 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0005_remove_bankdetails_account_type'),
        ('userModule', '0003_customuser_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminModule.bankdetails'),
        ),
    ]
