# Generated by Django 5.2.5 on 2025-09-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0003_alter_personaldetails_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_id',
            new_name='tracking_id',
        ),
    ]
