# Generated by Django 5.2.5 on 2025-08-13 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0005_remove_bankdetails_account_type'),
        ('userModule', '0004_customuser_default_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='default_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminModule.bankdetails'),
        ),
    ]
