# Generated by Django 5.2.5 on 2025-09-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0005_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
