# Generated by Django 5.2.5 on 2025-08-13 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0006_project_created_by_alter_project_bank_details_and_more'),
        ('userModule', '0005_alter_customuser_default_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminModule.institution'),
        ),
        migrations.AlterField(
            model_name='selectedtile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
