# Generated by Django 5.2.5 on 2025-09-19 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0006_alter_contactmessage_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='sent_at',
            new_name='sent_time',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='table_status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('reply_time', models.DateTimeField(auto_now_add=True)),
                ('table_status', models.BooleanField(default=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg', to='userModule.contactmessage')),
            ],
        ),
    ]
