# Generated by Django 5.2.5 on 2025-08-14 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0006_project_created_by_alter_project_bank_details_and_more'),
        ('userModule', '0006_alter_customuser_institution_alter_selectedtile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('table_status', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminModule.project')),
                ('tiles_bought', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userModule.selectedtile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_shot', models.ImageField(upload_to='screenshots/')),
                ('table_status', models.BooleanField(default=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userModule.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_pdf', models.FileField(upload_to='receipts/')),
                ('table_status', models.BooleanField(default=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userModule.transaction')),
            ],
        ),
    ]
