# Generated by Django 5.2.5 on 2025-09-19 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0004_alter_project_current_amount_and_more'),
        ('userModule', '0007_rename_sent_at_contactmessage_sent_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution', to='adminModule.institution'),
        ),
    ]
