# Generated by Django 5.2.5 on 2025-09-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0008_contactmessage_ins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-sent_time']},
        ),
        migrations.AlterModelOptions(
            name='messagereply',
            options={'ordering': ['-reply_time']},
        ),
    ]
