# Generated by Django 5.2.5 on 2025-10-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0009_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldetails',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='last_name',
        ),
    ]
