# Generated by Django 5.2.5 on 2025-11-12 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0010_rename_first_name_personaldetails_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt80mm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_80mm_pdf', models.FileField(upload_to='receipts/')),
                ('table_status', models.BooleanField(default=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userModule.transaction')),
            ],
        ),
    ]
