# Generated by Django 5.2.5 on 2025-11-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0011_receipt80mm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt80mm',
            name='receipt_80mm_pdf',
            field=models.FileField(upload_to='receipts80mm/'),
        ),
    ]
